import {
  siAngular,
  siC,
  siCplusplus,
  siDocker,
  siElectron,
  siExpress,
  siFastapi,
  siFirebase,
  siFlask,
  siGit,
  siGithubactions,
  siGo,
  siGooglecloud,
  siGraphql,
  siJavascript,
  siKubernetes,
  siLangchain,
  siLinux,
  siMongodb,
  siMysql,
  siNestjs,
  siNextdotjs,
  siNodedotjs,
  siPostgresql,
  siPython,
  siReact,
  siSupabase,
  siTerraform,
  siTypescript,
  siVercel,
} from "simple-icons";

const PATHS: Record<string, string> = {
  angular: siAngular.path,
  c: siC.path,
  cplusplus: siCplusplus.path,
  docker: siDocker.path,
  electron: siElectron.path,
  express: siExpress.path,
  fastapi: siFastapi.path,
  firebase: siFirebase.path,
  flask: siFlask.path,
  git: siGit.path,
  githubactions: siGithubactions.path,
  go: siGo.path,
  googlecloud: siGooglecloud.path,
  graphql: siGraphql.path,
  javascript: siJavascript.path,
  kubernetes: siKubernetes.path,
  langchain: siLangchain.path,
  linux: siLinux.path,
  mongodb: siMongodb.path,
  mysql: siMysql.path,
  nestjs: siNestjs.path,
  nextdotjs: siNextdotjs.path,
  nodedotjs: siNodedotjs.path,
  postgresql: siPostgresql.path,
  python: siPython.path,
  react: siReact.path,
  supabase: siSupabase.path,
  terraform: siTerraform.path,
  typescript: siTypescript.path,
  vercel: siVercel.path,
};

export function skillIconPath(slug: string): string | undefined {
  return PATHS[slug];
}
